environment:
  global:
    DOWNLOAD_DIR: C:\gtk-download
    PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\msys64\usr\bin
    PYTHON: C:\Python37\python.exe
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VER: "15"
      PLATFORM: "x86"

build_script:
  - git clone https://github.com/wingtk/gvsbuild.git
  - cd gvsbuild
  - git checkout 874592711b610b6f340f3453e414168acf999476
  - "%PYTHON% build.py build --archives-download-dir=%DOWNLOAD_DIR% --platform=%PLATFORM% --vs-ver=%VS_VER% gtk3 hicolor-icon-theme  adwaita-icon-theme"
  - cd .. && tar.exe -zcf gtk3-vs%VS_VER%-%PLATFORM%.tar.gz -C C:\gtk-build\gtk\Win32 release

artifacts:
  - path: gtk3-vs%VS_VER%-%PLATFORM%.tar.gz

test: off
